# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
#      - name: Cache pipenv
#        uses: actions/cache@v2
#        with:
#          # This path is specific to Ubuntu
#          path: ~/.cache/pip
#          # Look to see if there is a cache hit for the corresponding requirements file
#          key: ${{ runner.os }}-pip-${{ hashFiles('pipenv') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
#            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          export PYTHONPATH=:$(pwd):$PYTHONPATH
          pipenv run pytest ./tests/
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
