# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Virtual Env
        run: |
          virtualenv venv
          source venv/bin/activate
      - name: Run Unit Tests
        run: |
          export PYTHONPATH=:$(pwd):$PYTHONPATH
          python -c "import sys; print(sys.version)"
          cat Pipfile > Pipfile.tmp
          cat Pipfile.tmp | sed "s/= \"3.8\"/= \"${{ matrix.python-version }}\"/" > Pipfile
          pipenv install --dev
          python -c "import sys; print(sys.version)"
          pipenv run pytest -so xfail_strict=True --durations 10 --maxfail 10 --cov ./ --cov-report html --cov-report xml --junitxml test-reports/tests-${{ matrix.python-version }}.xml --cov-config=./tests/.coveragerc ./tests/
      # Set up posting code coverage to CodeCov.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
